apiVersion: v1
kind: Service
metadata:
  name: zk-server-2
spec:
  selector:
    zkserver: "2"
  ports:
  - name: client
    protocol: TCP
    port: 2181
  - name: leader
    protocol: TCP
    port: 2888
  - name: election
    protocol: TCP
    port: 3888

